### ISSUE TITLE
[feat] 添加“正在输入”的Notify支持

### ISSUE THREAD

**Issue by XeronOwO** [XeronOwO/Makabaka#5]
> ```
> [02:26:58 DBG] [de432cc7-d0fc-499f-a8e2-e86bad873228]接收数据：{"time":1726252018,"self_id":999999999,"post_type":"notice","notice_type":"notify","sub_type":"input_status","status_text":"对方正在输入...","event_type":1,"user_id":1012803704,"group_id":0}
> 
> [02:26:58 ERR] [de432cc7-d0fc-499f-a8e2-e86bad873228]处理数据时出现异常
> System.Exception: 不支持的notice_type：notify
>    at Makabaka.Utils.DataProcessor.ProcessNotice(String data, JObject json) in D:\ProgramRepos\Makabaka-main\Makabaka\Utils\DataProcessor.cs:line 217
>    at Makabaka.Utils.DataProcessor.ProcessPost(String data, JObject json) in D:\ProgramRepos\Makabaka-main\Makabaka\Utils\DataProcessor.cs:line 91
>    at Makabaka.Utils.DataProcessor.Process(String data) in D:\ProgramRepos\Makabaka-main\Makabaka\Utils\DataProcessor.cs:line 73
>    at Makabaka.Network.ForwardWebSocketContext.MessageReceived(Object sender, MessageReceivedEventArgs e) in D:\ProgramRepos\Makabaka-main\Makabaka\Network\ForwardWebSocketContext.cs:line 97
> ```
> 
> 我拿手机给机器人打消息（还没发出去的时候）就会发生报错（不影响程序），你看是不是要修
> 
> _Originally posted by @Pinkuburu in https://github.com/XeronOwO/Makabaka/issues/3#issuecomment-2349809572_

加入日程

**Comment by XeronOwO** [comment]
@Pinkuburu
想问下上面的那个notify是哪个机器人客户端的通知？
这个属于是在[Onebot11](https://github.com/botuniverse/onebot-11/blob/master/event/notice.md)协议之外的内容了，能不能给下完整的参数格式？这样我好写支持

**Comment by Pinkuburu** [comment]
感谢你的关注，我应该用的是https://github.com/NapNeko/NapCatQQ
给您造成麻烦了，不好意思

**Comment by XeronOwO** [comment]
[1f53016](https://github.com/XeronOwO/Makabaka/commit/1f530169a26881e585d77ec51b048e7e3838d120) 中已经添加支持。
但我没用过NapCatQQ，没法做测试。
另外，之前Makabaka写的太屎山了，现在在重构2.0，部分API还在开发中。很多代码逻辑进行了重构，如果基于之前的项目开发，可能需要改动一些代码才能运行。
